#!/bin/bash

export HTTP_PROXY=http://msk-kwts01.corp.suek.ru:3128
export HTTPS_PROXY=http://msk-kwts01.corp.suek.ru:3128
export http_proxy=$HTTP_PROXY
export https_proxy=$HTTPS_PROXY
# Change the shell prompt to reflect the selected node
export PS1="[\[\033[01;33m\]INTERNET\[\033[00m\]] \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

exec bash --rcfile <(
cat <<'EOF'
export PS1="[\[\033[01;33m\]INTERNET\[\033[00m\]] \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
# Custom aliases
# NONE
EOF
)

